[project]
name = "pySigma-backend-sqlite"
version = "1.2.0"
description = "pySigma sqlite backend"
readme = "README.md"
authors = [
    { name = "wagga" }
]
license = "LGPL-3.0-only"

[tool.poetry]
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.10"
pysigma = "^1"

[tool.poetry.group.dev.dependencies]
black = "^24.1"
pytest = "^8.0"
pytest-cov = "^4.1"
coverage = "^7.4"


[tool.pytest.ini_options]
filterwarnings = [
    # Suppress pyparsing deprecation warning from pySigma library
    "ignore:'parseString' deprecated:DeprecationWarning",
]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = []

[tool.pdm.build]
includes = ["sigma"]
[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Repository = "https://github.com/SigmaHQ/pySigma-backend-sqlite"

[project.group.dev.dependencies]
pytest = "^8.0"
pytest-cov = "^4.1"
coverage = "^7.4"




